<?php
/**
 * Lista de Domínios de Email Temporário/Descartável
 * Atualizada em: 12/01/2026
 * 
 * Esses domínios são conhecidos por oferecer emails descartáveis
 * que são frequentemente usados para spam, fraude ou abuso.
 * 
 * Fonte: Compilação de listas públicas (mailchecker, disposable-email-domains)
 */

return [
    // Populares Internacionais
    '10minutemail.com',
    '10minutemail.net',
    '10minutemail.org',
    'tempmail.com',
    'temp-mail.org',
    'temp-mail.io',
    'guerrillamail.com',
    'guerrillamail.org',
    'guerrillamail.net',
    'guerrillamail.biz',
    'guerrillamailblock.com',
    'sharklasers.com',
    'grr.la',
    'mailinator.com',
    'mailinator.net',
    'mailinator.org',
    'mailinator2.com',
    'maildrop.cc',
    'yopmail.com',
    'yopmail.fr',
    'yopmail.net',
    'throwaway.email',
    'throwawaymail.com',
    'fakeinbox.com',
    'fakemailgenerator.com',
    'dispostable.com',
    'disposableemailaddresses.com',
    'mailnesia.com',
    'trashmail.com',
    'trashmail.net',
    'trashmail.org',
    'trashmail.me',
    'trashemail.de',
    'getairmail.com',
    'getnada.com',
    'mohmal.com',
    'emailondeck.com',
    'tempail.com',
    'tempr.email',
    'discard.email',
    'discardmail.com',
    'spamgourmet.com',
    'mytemp.email',
    'mt2015.com',
    'mt2014.com',
    
    // Brasileiros / Português
    'emailtemporario.com.br',
    'tempinbox.com',
    'emailfake.com',
    
    // Outros Populares
    'mailcatch.com',
    'inbox.lv',
    'dropmail.me',
    'instantemailaddress.com',
    'mintemail.com',
    'mailnull.com',
    'mailscrap.com',
    'emailsensei.com',
    'safetymail.info',
    'spambox.us',
    'spamfree24.org',
    'spamfree.eu',
    'crazymailing.com',
    'tempsky.com',
    'tempmailaddress.com',
    'burnermail.io',
    'inboxkitten.com',
    'emailfake.com',
    'fakeemail.net',
    'spamdecoy.net',
    'inboxbear.com',
    'boximail.com',
    'onewaymail.com',
    'emailisvalid.com',
    'anonymbox.com',
    'jetable.org',
    'soodo.net',
    'mailsac.com',
    'hushmail.me',
    'emkei.cz',
    'fakemail.fr',
    'throwam.com',
    'mvrht.net',
    'nwytg.net',
    'tmpmail.net',
    'tmpmail.org',
    'tempomail.fr',
    'temporaryemail.net',
    'temporaryemail.us',
    'tempinbox.co.uk',
    'tempmailgen.com',
    
    // Variantes comuns
    '33mail.com',
    'mailexpire.com',
    'mailforspam.com',
    'spamavert.com',
    'antispam.de',
    'kasmail.com',
    'spamherelots.com',
    'emailthe.net',
    'binkmail.com',
    'safetypost.de',
    'veryrealemail.com',
    'veryrealmail.com',
    
    // Novos em 2025-2026
    'emailnax.com',
    'luxusmail.org',
    'email-fake.com',
    'emailondeck.com',
    'cmail.club',
    'cmail.net',
    'mailpick.biz',
    'nada.email',
    'tempm.com',
    'wegwerfmail.de',
    'wegwerfmail.net',
    'wegwerfmail.org',
    'fakeemailgenerator.net',
    'smailpro.com',
    'zetmail.com',
    
    // Genéricos suspeitos
    'example.com',
    'example.org',
    'example.net',
    'test.com',
    'teste.com',
    'teste.com.br',
];
